version: "3.8"
services:

  skistation:
    container_name: skistation
    image: bohboh283/skistation
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/SkiStationDB?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      - mysql
    volumes:
      - .m2:/root/.m2



  mysql:
    image: "mysql:5.7"
    container_name: mysql-container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD : "yes"
      MYSQL_DATABASE: SkiStationDB
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql


volumes:
  db :