version: "3.8"
services:

  skistation:
    container_name: skistation
    image: skistation
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/SkiStationDB?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      spring.jpa.hibernate.ddl-auto : update
      spring.jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2



  mysqldb:
    image: "mysql:5.7"
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=SkiStationDB
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql


volumes:
  db :